# Generated by Django 4.2.4 on 2024-03-14 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 11, 18, 15, 300375, tzinfo=datetime.timezone.utc)),
        ),
    ]
