# Generated by Django 4.2.4 on 2023-12-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_follows_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dweet', to='api.dweet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='api.profile')),
            ],
        ),
    ]
